services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TRAW\VhsCol\:
    resource: '../Classes/*'

  TRAW\VhsCol\Configuration\TcaOptionsMap:
    public: true
  TRAW\VhsCol\ViewHelpers\Media\Source\ContainerMaxWidthViewHelper:
    public: true

  TRAW\VhsCol\DataProcessing\FlexFormProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'traw-flexform'
  TRAW\VhsCol\DataProcessing\Records\RecordDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'traw-record-data'

  TRAW\VhsCol\DataProcessing\GalleryProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'traw-gallery'
  TRAW\VhsCol\DataProcessing\Menu\SplitMenuProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'traw-splitmenu'
  TRAW\VhsCol\Listener\PageTsConfig:
    tags:
      - name: event.listener
        identifier: 'txvhscol-page-tsconfig'
  TRAW\VhsCol\Listener\BootCompleted:
    tags:
      - name: event.listener
        identifier: 'txvhscol-boot-completed'

