services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TRAW\VhsCol\:
    resource: '../Classes/*'

  TRAW\VhsCol\DataProcessing\FlexFormProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'traw-flexform'

  TRAW\VhsCol\DataProcessing\GalleryProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'traw-gallery'
        
  TRAW\VhsCol\Listener\PageTsConfig:
    tags:
      - name: event.listener
        identifier: 'txvhscol-page-ts-config'

